name: psychwm
channels:
  - conda-forge
dependencies:
  - python=3.10

  # R runtime + Jupyter kernel
  - r-base
  - r-irkernel

  # R packages you use
  - r-here
  - r-readxl
  - r-dplyr
  - r-tidyr
  - r-tibble
  - r-knitr
  - r-rmarkdown
  - r-psych
  - r-semtools
  - r-mvn
  - r-mice
  - r-openxlsx
  - r-sjmisc
  - r-semplot
